titulo_semanal = "Weekly Summary 03/06/2023"
subtitulo_semanal = " **Week of rises in the stock markets that close a complicated month of February with falls of more than 2% in the case of the US stock markets and slight rises in the European ones**"
resumen_semanal = "The context of macroeconomic data does not dispel inflationary fears, with inflation data in Germany, France and the Eurozone as a whole surprising on the rise and with low requests for unemployment benefits, demonstrating the strength of employment in the US. The interventions last Thursday by Waller and Bostic, both members of the FED, focused on highlighting the need to be patient to see the effects of rate hikes on the economy, marking a discourse more oriented towards a 25 bps rise in the next meeting against expectations of 50 bps. On the European side, Christine Lagarde stated that at the ECB meeting on March 16, the decision to raise 50 bps seems clear. There were other macro references that left a mixed tone, with a focus on the US, such as the outstanding data from the ISM Manufacturing that remains at 47.7, indicating economic contraction, despite the fact that Services remains resilient at 55.1. On the other hand, we saw the rise in home sales in January (8.1%), the decline in global orders for durable goods, which registered their largest decline since April 2020, while, on the other hand, inventories Retail (excluding autos) rose slightly and wholesale inventories fell for the first time since July 2020. In this context, bond markets reacted with a further inversion of the curve in the US with the 2-year yield rising 80 bps and the 10-year bond standing above 4%, a similar case in Europe with the highest IRRs seen in the different tranches of the German bond since the previous crisis."

titulo_cuerpo = "" 
cuerpo_semanal =""

title_renta_variable = "**Equities**"
renta_variable = "**Rises in the US stock markets**, supported by the slight improvement in the manufacturing PMI and the prudent tone of the statements by the members of the FED. The S&P 500 rose 1.90% and the tech NASDAQ 2.58%. As regards sectors, it is worth highlighting the increases in Basic Resources, especially due to the relevant rises in the prices of oil and natural gas, and in Communication Services, compared to the falls in Basic Consumption and Utilities. **We also saw rises in the European stock markets** that seemed more focused on the signs of improvement in the economic outlook, even in the delicate inflationary moment that is the current one. The Stoxx 600 rose 1.43% supported by the Commodities and Energy sectors, also supported by increases in gas and oil. On the other hand, the most defensive sectors such as Health or Utilities were the sectors most affected. **Positive week in Emerging Markets**, highlighting the rises in the Chinese CSI and the Hong Kong Hang Seng with 2.8%, given the rebound in the PMI data (52.6 vs. 50.1 previously) and new home sales ( +14.9% vs. the previous month), which especially favored Chinese equities but also the rest of the emerging markets given the weight and importance of the Chinese economy. In particular, the good data from the manufacturing sector was seen as an incentive to rise after several weeks of negative news."

title_renta_fija = "**Fixed income**"
renta_fija = "The fall in bond prices continues, given less optimistic prospects than at the beginning of the year regarding the moderation of prices, which leaves central banks with no way out in their fight against inflation. There were no big moves in credit spreads, which remain far from recession levels. Due to the large issuance volumes seen in recent years, companies can endure 1 or 2 years with low financing volumes, thus avoiding a greater impact from rate increases. Peripheral risk premiums in Europe also continue at very contained levels and do not appear to be showing any weakness."

title_divisa_mater = "**Currencies and Commodities**"
divisa_materia = "The concern caused by the general inflationary outlook keeps the bond markets under tension and in a context of high IRRs both in Europe and in the US, with the 10-year Treasury at levels of 4%. The inversion of the curve is increasing, reaching a record of 40 years in the inversion of the 2-10 year curve, a clear indicator of recession, with short periods such as 2 years at an IRR of 4.81%."

title_esta_semana = "**This Week: Relevant news that can affect the price of assets**"
esta_semana1 = " 1. On :orange[**_Monday_**] We will have the Factory orders for the month of January in the US and the retail sales data for the month of January in the Eurozon."
esta_semana2 = " 2. On :orange[**_Tuesday_**], We will have the preliminary data for factory orders for the month of January in Germany and the preliminary data for consumer credit for the month of January in the US."
esta_semana3 = " 3. On :orange[**_Wednesday_**], We will get the jobs data and the final GDP data for the Eurozone. In the US, the ADP Employment Survey as well as the JOLTs Survey of job offers."
esta_semana4 = " 4. :orange[**_Thursday_**], Nothing relevant"
esta_semana5 = " 4. :orange[**_Friday_**], We will have the unemployment data and the average hourly wage in the US for the month of February."