titulo_semanal = "Weekly Summary 02/27/2023"
subtitulo_semanal = " **The equity markets seem to have definitively put a stop to the euphoria with which they began this year 2023**"
resumen_semanal = "Although they continue to show surprising resilience in some cases, especially if we take into account the macro data published in recent weeks. The latest data known has been that of the American PCE, which has also surprised on the rise, rebounding even above the previous month. In particular, the behavior of the European indices is striking, where the argument of low valuations and having saved a first 'match ball' with respect to gas prices, seems sufficient to counteract the challenges and structural problems that the region is suffering from. In the fixed income markets, the already mentioned negative surprises seen in prices do seem to have changed the perception of investors. They now not only see it as difficult for there to be cuts in rates before the end of the year, but also seem to have also lengthened their expectations in the type of arrival. Finally, the minutes of the last meeting of the FED focused part of the attention of investors, in which a certain moderation of the restrictive policy carried out by the institution in 2022 has been reflected, although it is true that in the The debate left the door open to carry out several more increases if prices did not follow the path that was foreseen. This speed in the moderation of inflation is precisely what the data published in February make us think is not happening, and therefore the change in tone in the discourse has already become somewhat outdated. Therefore, a greater aggressiveness in the central bank's stance can be seen at the next meeting on March 21-22."

titulo_cuerpo = "" 
cuerpo_semanal =""

title_renta_variable = "**Equities**"
renta_variable = "A week of falls for the indices in the United States, the data released in recent weeks have influenced investor confidence regarding the course of inflation and its resilience. Because of this, some of the sectors that were establishing themselves as winners at the beginning of the year are the same ones that are suffering the most from this change of scenery. Last week the sectors that did the worst were: Communication, Consumer Discretionary, Real Estate and Technology. In the same way, the most defensive sectors followed the opposite path, showing a better performance. The European stock markets followed a similar path to their American counterparts, although a smaller fall has allowed them to extend their advantage so far this year. Those sectors most sensitive to the evolution of interest rates and the economic cycle were the most affected, on the contrary, the defensive sectors and banking (the sector most favored by the rate hike) were the ones that did best. Bad week for the emerging markets that continue to be at the tail end in terms of returns in 2023. The winning and losing sectors of last week coincide with the rest of the geographies, not in vain are we still in a highly globalized world, and both the year In the past like this, it has been the macroeconomic aspects that have led the returns of the main financial assets."

title_renta_fija = "**Fixed income**"
renta_fija = "The fall in bond prices continues, given less optimistic prospects than at the beginning of the year regarding the moderation of prices, which leaves central banks with no way out in their fight against inflation. There were no big moves in credit spreads, which remain far from recession levels. Due to the large issuance volumes seen in recent years, companies can endure 1 or 2 years with low financing volumes, thus avoiding a greater impact from rate increases. Peripheral risk premiums in Europe also continue at very contained levels and do not appear to be showing any weakness."

title_divisa_mater = "**Currencies and Commodities**"
divisa_materia = "Strong revaluation of the dollar that continues its recovery thanks to the resilience of the American economy and the slow moderation of prices. Gold is another of those affected in the month of February and has already lost all the advantage it had achieved in the previous month."

title_esta_semana = "**This Week: Relevant news that can affect the price of assets**"
esta_semana1 = " 1. On :orange[**_Monday_**] On Monday afternoon, we will know the volume of durable goods orders for the month of January in the United States."
esta_semana2 = " 2. On :orange[**_Tuesday_**] Tuesday, we will have the preliminary CPI for France and Spain for the month of February and in the afternoon the consumer confidence survey of the Conference Board in the US will be published."
esta_semana3 = " 3. On :orange[**_Wednesday_**] We begin the month of March on Wednesday with important data at a global level. Manufacturing PMI data will be published in China and the United States, and we will also know labor market data in Germany.."
esta_semana4 = " 4. :orange[**_Thursday_**] On Thursday we will have the preliminary CPI for the Euro Zone in February and the unemployment rate for the region in January."
esta_semana5 = " 4. :orange[**_Friday_**] We will end the week with some publications to which the market will pay special attention, they are the PMIs of the service sector in China and the US."